config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: :signup
  get 'signin', to: 'user_sessions#new', as: :signin
  get 'signout', to: 'user_sessions#destroy', as: :signout

  resources :posts, only: [:index]

  resources :subcreddits, path: 'c', except: [:destroy] do
    resources :posts, path: '', constraints: { id: /\d+\-.+/ }, except: [:index] do
      resources :comments, path: '', constraints: { id: /\d+/ }, except: [:index]
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, path: 'u', only: [:show, :new, :create]

  root to: 'posts#index'
end

app/models/comment.rb
# models/comment.rb
class Comment < ActiveRecord::Base
  has_ancestry

  belongs_to :user
  belongs_to :post, counter_cache: true

  delegate :username, to: :user, prefix: true
  delegate :subcreddit, to: :post, prefix: true

  validates :content, presence: true

  def content
    destroyed? ? '[deleted]' : read_attribute(:content)
  end

  def destroy
    update_attribute(:deleted_at, Time.now)
  end

  def destroyed?
    self.deleted_at != nil
  end
end

app/controllers/comments_controller.rb
# controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :set_post
  before_filter :set_subcreddit
  after_action :verify_authorized

  def show
    @comments = @comment
                  .subtree
                  .includes(:post, :user)
                  .arrange(order: :created_at)

    authorize @comment
  end

  def new
    @comment = Comment.new(params[:parent_id])

    authorize @comment
  end

  def create
    @comment = @post.comments.build comment_params
    @comment.user = current_user

    authorize @comment

    if @comment.save
      flash[:notice] = 'Comment saved'
    else
      flash[:alert] = 'Comment could not be saved'
    end

    redirect_to subcreddit_post_path(@subcreddit, @post)
  end

  def edit
    authorize @comment
  end

  def update
    authorize @comment

    if @comment.update comment_params
      redirect_to subcreddit_post_path(@subcreddit, @post),
        notice: 'Comment updated'
    else
      render :edit
    end
  end

  def destroy
    authorize @comment

    @comment.destroy
    redirect_to subcreddit_post_path(@subcreddit, @post),
      notice: 'Comment deleted'
  end

  private

  def set_subcreddit
    @subcreddit = Subcreddit.friendly.find(params[:subcreddit_id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:parent_id, :content)
  end
end

app/helpers/comments_helper.rb
# helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment, post: comment.post, subcreddit: comment.post_subcreddit) +
        content_tag(:div,
                    nested_comments(sub_comments),
                    class: 'nested_comments')
    end.join.html_safe
  end
end

app/views/comments/_comment.html.slim
.comment
  p.details
    == link_to comment.user_username, comment.user
    = " X points #{distance_of_time_in_words comment.created_at, Time.now} ago"
  p.content= comment.content
  ul.links.list-inline
    li= link_to 'permalink', subcreddit_post_comment_path(subcreddit, post, comment)
    li= link_to 'save', ''
    - if comment.parent
      li= link_to 'parent', subcreddit_post_comment_path(subcreddit, post, comment.parent)
    li= link_to 'edit', edit_subcreddit_post_comment_path(subcreddit, post, comment)
    li= link_to 'delete', subcreddit_post_comment_path(subcreddit, post, comment), method: :delete
    li= link_to 'spam', ''
    li= link_to 'remove', ''
    li= link_to 'give gold', ''

app/views/comments/_form.html.slim
= simple_form_for [subcreddit, post, comment] do |f|
  - if local_assigns.has_key?(:parent) && parent
    = f.hidden_field :parent_id, value: parent.id
  .form-inputs
    = f.input :content, label: false
  .form-actions
    = f.button :submit

app/views/comments/edit.html.slim
h1 Edit comment
== render 'form', subcreddit: @subcreddit, post: @post, comment: @comment

app/views/comments/show.html.slim
- content_for(:title, link_to(@subcreddit.name, @subcreddit))
== render 'posts/post', post: @post
.alert.alert-info.in-page
  p you are viewing a single comment's thread.
  p #{link_to 'view the rest of the comments', subcreddit_post_path(@subcreddit, @post)} →
- if policy(:comment).new?
  = "Commenting as: #{current_user.username}"
  == render 'comments/form', subcreddit: @subcreddit, post: @post, comment: @post.comments.build, parent: @comment
.comments.contents
  == nested_comments(@comments)