config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: :signup
  get 'signin', to: 'user_sessions#new', as: :signin
  get 'signout', to: 'user_sessions#destroy', as: :signout

  resources :posts, only: [:index]

  resources :subcreddits, path: 'c', except: [:destroy] do
    resources :posts, path: '', constraints: { id: /\d+\-.+/ }, except: [:index] do
      resources :comments, path: '', constraints: { id: /\d+/ }, except: [:index]
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, path: 'u', only: [:show, :new, :create]

  root to: 'posts#index'
end

app/models/post.rb
# models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :subcreddit

  has_many :comments

  delegate :username, to: :user, prefix: true
  delegate :slug, to: :subcreddit, prefix: true

  validates :title,
    presence: true,
    length: { maximum: 300 }

  validates :content,
    length: { maximum: 15000 }

  def to_param
    # This "just works" because of the way Rails IDs work.  .to_i must be run on
    # any incoming ID.  "1-title-parameterized" will automatically be converted
    # to 1 and "2-title-paramerterized-with-number-2" will automatically be
    # converted to 2.  This gives us desired functionality without adding code
    # to properly handle retrieving based on slug.  Hopefully, this does not
    # cause issues later on.
    "#{self.id}-#{self.title.parameterize}"
  end

  def comments?
    self.comments_count != 0
  end
end

app/controllers/posts_controller.rb
# controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_post, except: [:index, :new, :create]
  before_filter :set_subcreddit
  after_action :verify_authorized

  def index
    @posts = Post.includes(:subcreddit, :user).all

    authorize Post
  end

  def show
    @comments = @post.comments.includes(:user).arrange(order: :created_at)

    authorize @post
  end

  def new
    @post = Post.new

    authorize @post
  end

  def create
    @post = @subcreddit.posts.build(post_params)
    @post.user = current_user

    authorize @post

    if @post.save
      redirect_to subcreddit_post_path(@subcreddit, @post),
        notice: 'Post created'
    else
      render :new
    end
  end

  def edit
    authorize @post
  end

  def update
    authorize @post

    if @post.update(post_params)
      redirect_to subcreddit_post_path(@subcreddit, @post),
        notice: 'Post was updated'
    else
      render :edit
    end
  end

  def destroy
    authorize @post

    @post.destroy

    redirect_to subcreddits_path(@subcreddit), notice: 'Post was deleted'
  end

  private

  def post_params
    params.require(:post).permit(:title, :link, :content, :subcreddit_id)
  end

  def set_subcreddit
    @subcreddit = Subcreddit.find_by_slug(params['subcreddit_id'])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/posts/_form.html.slim
.col-md-9
  = simple_form_for [subcreddit, post] do |f|
    .form-inputs
      = f.input :title, class: 'inline-block'
      = f.input :link
      = f.input :content
    .form-actions
      = f.button :submit

app/views/posts/_post.html.slim
.posts.contents
  .post.show
    p.title= link_to post.title, [post.subcreddit, post]
    p.details
      = "submitted #{distance_of_time_in_words post.created_at, Time.now} ago by "
      == link_to post.user_username, post.user
    p.content= post.content
    ul.links.list-inline
      li= link_to "#{post.comments_count} comments", subcreddit_post_path(post.subcreddit, post)
      li= link_to 'share', ''
      li= link_to 'edit', edit_subcreddit_post_path(post.subcreddit, post)
      li= link_to 'save', ''
      li= link_to 'hide', ''
      li= link_to 'remove', ''
      li= link_to 'approve', ''
      li= link_to 'nsfw', ''

app/views/posts/_post_meta.html.slim
.posts.contents
  ul
    - posts.order('created_at DESC').each_with_index do |post, rank|
      li
        .post
          p.title= link_to post.title, subcreddit_post_path(post.subcreddit, post)
          p.details
            = "submitted #{distance_of_time_in_words post.created_at, Time.now} ago by "
            == link_to post.user_username, post.user
            - if subcreddit == nil
              = " to "
              == link_to "/c/#{post.subcreddit_slug}", post.subcreddit
          ul.links.list-inline
            li= link_to "#{post.comments_count} comments", subcreddit_post_path(post.subcreddit, post)
            li= link_to 'share', ''

app/views/posts/edit.html.slim
= render 'form', subcreddit: @subcreddit, post: @post

app/views/posts/index.html.slim
- subcreddit_name
== render 'post_meta', posts: @posts, subcreddit: @subcreddit

app/views/posts/new.html.slim
= render 'form', subcreddit: @subcreddit, post: @post

app/views/posts/show.html.slim
- content_for(:title, link_to(@subcreddit.name, @subcreddit))
== render 'post', post: @post
- if @post.comments?
  .title= "all #{@post.comments_count} comments"
- else
  .title= "no comments (yet)"
- if policy(:comment).new?
  = "Commenting as: #{current_user.username}"
  == render 'comments/form', subcreddit: @subcreddit, post: @post, comment: @post.comments.build, parent: nil
.comments.contents
  == nested_comments(@comments)