config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: :signup
  get 'signin', to: 'user_sessions#new', as: :signin
  get 'signout', to: 'user_sessions#destroy', as: :signout

  resources :posts, only: [:index]

  resources :subcreddits, path: 'c', except: [:destroy] do
    resources :posts, path: '', constraints: { id: /\d+\-.+/ }, except: [:index] do
      resources :comments, path: '', constraints: { id: /\d+/ }, except: [:index]
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, path: 'u', only: [:show, :new, :create]

  root to: 'posts#index'
end

app/controllers/application_controller.rb
# controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :current_session
  helper_method :logged_in?

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def current_user
    @current_user ||= User.find(current_session[:user_id]) if current_session
    @current_user ||= GuestUser.new
  end

  def current_session
    @current_session ||= UserSession.authenticate(cookies[:user_session])
  end

  def logged_in?
    current_user.registered?
  end

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/helpers/application_helper.rb
# helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    bootstrap_classes[flash_type] || flash_type.to_s
  end

  def page_header
    content_for(:title) || ''
  end

  private

  def bootstrap_classes
    {
      'alert'   => 'alert-warning',
      'error'   => 'alert-danger',
      'notice'  => 'alert-info',
      'success' => 'alert-success'
    }
  end
end

app/views/application/_flash_message.html.slim
.alert.slide.up class=bootstrap_class_for(type)
  button.close type='button' data-dismiss='alert'
    span aria-hidden='true' &times;
    span.sr-only Close
  = message

app/views/application/_flash_messages.html.slim
- flash.each do |type, message|
  = render 'flash_message', type: type, message: message

app/views/application/_navbar.html.slim
.navbar.navbar-default.navbar-static-top.navbar-custom
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='.navbar-collapse'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .pull-left= link_to image_tag('logo.png', height: 44, class: 'logo'), root_path
      = link_to 'Creddit', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li= page_header
      ul.nav.navbar-nav.navbar-right
        - if logged_in?
          li= link_to 'Sign Out', signout_path
        - else
          li= link_to 'Create Account', signup_path
          li= link_to 'Sign In', signin_path

app/views/application/_sidebar.html.slim
.sidebar
  .input-group
    input.form-control type="text" placeholder="search"
    span.input-group-btn
      button.btn.btn-default type="button"
        span.glyphicon.glyphicon-search aria-hidden="true"

  - if policy(:post).new?
    - if @subcreddit && @subcreddit.id
      = link_to 'Submit a new link', new_subcreddit_post_path(@subcreddit), class: 'button btn btn-primary btn-block'
      = link_to 'Submit a new text post', new_subcreddit_post_path(@subcreddit), class: 'button btn btn-primary btn-block'
  - if policy(:subcreddit).new?
    = link_to 'Create your own subcreddit', new_subcreddit_path, class: 'button btn btn-primary btn-block'

  - if @subcreddit && @subcreddit.id && policy(@subcreddit).edit?
    .title Moderation Tools
    .box
      ul
        li= link_to 'subcreddit settings', edit_subcreddit_path(@subcreddit)
    .title Moderators
    .box
      ul
        li= link_to @subcreddit.owner_username, @subcreddit.owner